apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi-admin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi-admin
  template:
    metadata:
      labels:
        app: productapi-admin
    spec:
      containers:
      - name: productapi-admin
        image: us-central1-docker.pkg.dev/nagp-ctt/ecommerce-repo/productapi-admin:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: productapi-admin-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: productapi-admin
