---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi-admin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi-admin
  template:
    metadata:
      labels:
        app: productapi-admin
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          image: us-central1-docker.pkg.dev/nagp-ctt/ecommerce-repo/productapi-admin:latest
          name: productapi-admin
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: productapi-admin-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: productapi-admin
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: default
spec:
  rules:
    - host: adminapi.com
      http:
        paths:
          - backend:
              service:
                name: productapi-admin-service
                port:
                  number: 80
            path: /api/product
            pathType: Prefix
          - backend:
              service:
                name: productapi-admin-service
                port:
                  number: 80
            path: /api/product/item
            pathType: Prefix
          - backend:
              service:
                name: productapi-admin-service
                port:
                  number: 80
            path: /api/brand
            pathType: Prefix
          - backend:
              service:
                name: productapi-admin-service
                port:
                  number: 80
            path: /api/category
            pathType: Prefix