---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi-public
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi-public
  template:
    metadata:
      labels:
        app: productapi-public
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          image: us-central1-docker.pkg.dev/nagp-ctt/ecommerce-repo/productapi-public:latest
          name: productapi-public
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: productapi-public-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: productapi-public
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Authorization, Content-Type
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
  name: api-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: publicapi.com
      http:
        paths:
          - backend:
              service:
                name: productapi-public-service
                port:
                  number: 80
            path: /api/product/
            pathType: Prefix