apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchapi-public
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchapi-public
  template:
    metadata:
      labels:
        app: searchapi-public
    spec:
      containers:
      - name: searchapi-public
        image: us-central1-docker.pkg.dev/nagp-ctt/ecommerce-repo/searchapi-public:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: searchapi-public-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: searchapi-public
