services:
  userapi:
    image: userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile

  productapi:
    image: productapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
