apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            runAsUser: 0  # Run as root
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              value: 'Developer@0029'
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elastic-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi  # Adjust the size as needed
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  type: LoadBalancer   # Change here for external access
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
