---
apiVersion: v1
data:
  sa-password: RGV2ZWxvcGVyQDAwMg==
kind: Secret
metadata:
  name: sql-server-secret
type: Opaque
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  serviceName: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: sa-password
                  name: sql-server-secret
            - name: MSSQL_MEMORY_LIMIT_MB
              value: '2048'
          image: mcr.microsoft.com/mssql/server:2019-latest
          name: sql-server
          ports:
            - containerPort: 1433
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sql-data
      initContainers:
        - command: ['sh', '-c', 'chown -R 10001:10001 /var/opt/mssql']
          image: busybox
          name: init-permissions
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sql-data
      securityContext:
        fsGroup: 10001
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-data-pvc
        - name: init-sql
  volumeClaimTemplates:
    - metadata:
        name: sql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server
spec:
  clusterIP: None
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: sql-server