---
apiVersion: v1
kind: Secret
metadata:
  name: sql-server-secret
type: Opaque
data:
  sa-password: RGV2ZWxvcGVyQDAwMjk=  # Base64 encoded "Developer@0029"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  serviceName: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - name: sql-server
          image: mcr.microsoft.com/azure-sql-edge  # ✅ Azure SQL Edge image
          env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server-secret
                  key: sa-password
            - name: MSSQL_MEMORY_LIMIT_MB
              value: '1024'  # ✅ Adjusted for Azure SQL Edge (lightweight)
          ports:
            - containerPort: 1433
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: sql-data
              mountPath: /var/opt/mssql
      securityContext:
        fsGroup: 10001
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-data-pvc
  volumeClaimTemplates:
    - metadata:
        name: sql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi  # ✅ Reduced storage since Edge is lightweight

---
apiVersion: v1
kind: Service
metadata:
  name: sql-server
  namespace: default
spec:
  type: LoadBalancer  # ✅ Allows external access for Azure Data Studio
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
  selector:
    app: sql-server
