apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGODB_DATABASE: nagpdb
  MONGODB_ROOT_USERNAME: nagpadmin
  MONGO_SERVICE_NAME: mongodb

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGODB_ROOT_PASSWORD: TkFHUERCX1Bhc3N3b3Jk



