---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background-worker
  template:
    metadata:
      labels:
        app: background-worker
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          image: us-central1-docker.pkg.dev/nagp-ctt/ecommerce-repo/background-worker:TAG_PLACEHOLDER
          name: background-worker
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi