---
env:
  DEPLOYMENT_NAME: database-deployment
  GKE_CLUSTER: mcart-autopilot-cluster-1
  GKE_ZONE: us-central1
  IMAGE: database-deployment
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPOSITORY: ecommerce-repo
jobs:
  deploy-databases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      - name: Deploy SQL Server
        run: |
          kubectl apply -f ./CTT_Online_Shopping/K8s/databases/sql-server-deployment.yml

      # Deploy Elasticsearch
      - name: Deploy Elasticsearch
        run: |
          kubectl apply -f ./CTT_Online_Shopping/K8s/databases/elasticsearch-deployment.yml

      # Deploy Kafka
      # Deploy SQL Server
      # Get GKE credentials
      # Authenticate with Google Cloud
      # Checkout the code
      - name: Deploy Kafka
        run: |
          kubectl apply -f ./CTT_Online_Shopping/K8s/databases/kafka-deployment.yml
name: Deploy Databases and Kafka
'on':
  push:
    branches:
      - main
    paths:
      - CTT_Online_Shopping/K8s/databases/**